### ISSUE TITLE
[Bug] New listing with individual units throws error

### ISSUE THREAD

**Issue by abbiefarr** [CityOfDetroit/bloom#582]
STEPS TO REPRODUCE:
1. Log into the partner portal as an admin
2. Open the form to add a new listing
3. Add an individual unit to the new listing
4. Submit

EXPECTED RESULTS:
Listing would be successfully submitted

OBSERVED RESULTS:
Server error:
```
TypeError: Cannot read property 'name' of null
[0]     at /usr/local/google/home/afarr/Documents/bloom/backend/core/dist/src/shared/units-transformations.js:205:41
[0]     at Array.forEach (<anonymous>)
[0]     at Object.exports.summarizeUnitsByTypeAndRent (/usr/local/google/home/afarr/Documents/bloom/backend/core/dist/src/shared/units-transformations.js:202:11)
[0]     at Object.exports.summarizeUnits (/usr/local/google/home/afarr/Documents/bloom/backend/core/dist/src/shared/units-transformations.js:271:38)
[0]     at ListingsService.addUnitsSummarized (/usr/local/google/home/afarr/Documents/bloom/backend/core/dist/src/listings/listings.service.js:165:63)
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[0]     at async ListingsService.findOne (/usr/local/google/home/afarr/Documents/bloom/backend/core/dist/src/listings/listings.service.js:157:9)
[0]     at async ListingsController.retrieve (/usr/
```

ADDITIONAL INFORMATION:

**Comment by abbiefarr** [comment]
This appears to have been fixed upstream.
