### ISSUE TITLE
[Bug] "Unit Availability" filtering has unexpected behavior

### ISSUE THREAD

**Issue by anders-schneider** [CityOfDetroit/bloom#682]
[REMEMBER: a bug should be understandable years later by someone who will never talk to the reporter or assignee.]

STEPS TO REPRODUCE (and observed results):
(Note I ran these steps on the deployed app)
1. Open the "all listings" view (notice that there are 11 total listings)
2. Filter by "Has Availability" --> 1 listing (Treymore Apartments)
3. Filter by "No Availability" --> 1 listing (Treymore Apartments)
4. Filter by "Waitlist" --> 2 listings (Morton Manor, New Center Square)

EXPECTED RESULTS:
The results above seem to violate two expectations:
- Treymore Apartments should show up for _either_ "Has Availability" or "No Availability" (not both).
- Each of the 11 listings should have be present in exactly one of the three buckets ("Has Availability", "No Availability", or "Waitlist") but instead it seems like most listings are absent from all three.

**Comment by plunkettgoogle** [comment]
I think filtering in general is broken right now... When I try to make a filter with 0 or more bedrooms (i.e. `listings/filtered?page=1&bedrooms=0`), it doesn't show any results, and I see the following stack trace in the logs:

```
 BACKEND_CORE [Nest] 1973932   - 11/11/2021, 11:39:08 AM   [ExceptionsHandler] missing FROM-clause entry for table "unittyperef" +6689ms
 BACKEND_CORE QueryFailedError: missing FROM-clause entry for table "unittyperef"
 BACKEND_CORE     at new QueryFailedError (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/error/QueryFailedError.js:12:28)
 BACKEND_CORE     at PostgresQueryRunner.<anonymous> (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:248:31)
 BACKEND_CORE     at step (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/node_modules/tslib/tslib.js:143:27)
 BACKEND_CORE     at Object.throw (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/node_modules/tslib/tslib.js:124:57)
 BACKEND_CORE     at rejected (/usr/local/google/home/patplunkett/bloom/node_modules/typeorm/node_modules/tslib/tslib.js:115:69)
 BACKEND_CORE     at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by plunkettgoogle** [comment]
Actually, in this specific case, it appears to be an actual bug in query builder code.

The original problem that @anders-schneider is describing is still present with my fix, however.

**Comment by plunkettgoogle** [comment]
I think I've narrowed down why @anders-schneider was seeing this issue:

 * the "has availability" filter will return listings that own at least one unit type with > 0 `total_available`, whereas
 * the "no availability" filter will return listings that own at least one unit type with exactly 0 `total_available`

Nulls are ignored. It just so happens that the Treymore Apartments is the only listing with non-null unit availabilities, with one have 0 available and the other having 4 available:

```
bloom=# SELECT "listings"."name", "unitType"."name", "unitsSummary"."total_available" FROM "listings" "listings" LEFT JOIN "units_summary" "unitsSummary" ON "unitsSummary"."listing_id"="listings"."id" LEFT JOIN "unit_types" "unitType" ON "unitType"."id"="unitsSummary"."unit_type_id" GROUP BY "listings"."id", "unitType"."name", "unitsSummary"."total_available" ORDER BY "listings"."updated_at" DESC;
           name            |   name    | total_available 
---------------------------+-----------+-----------------
 Treymore Apartments       | twoBdrm   |               4
 Treymore Apartments       | studio    |               0
 Oak Village Independence  | oneBdrm   |                
 New Center Square         | threeBdrm |                
 New Center Pavilion       | twoBdrm   |                
 New Center Pavilion       | oneBdrm   |                
 New Center Commons        | twoBdrm   |                
 New Center Commons        | studio    |                
 New Center Commons        | oneBdrm   |                
 Morton Manor              | oneBdrm   |                
 Morningside Commons Multi | fourBdrm  |                
 Morningside Commons Multi | twoBdrm   |                
 Morningside Commons Multi | threeBdrm |                
 Morang Apartments         | oneBdrm   |                
 MLK Homes                 | threeBdrm |                
 MLK Homes                 | fourBdrm  |                
 Melrose Square Homes      | fourBdrm  |                
 Melrose Square Homes      | threeBdrm |                
 Medical Center Village    | oneBdrm   |                
 Medical Center Village    | threeBdrm |                
 Medical Center Village    | twoBdrm   |                
 ```

I think what needs to happen here is that we should apply the "has/no availability" filter _after_ all the other filters have been applied, and then base it on the sum of `unitsSummary.total_available`. I don't really have a good idea of how to do that with the typeorm stuff, so I'ma just fix the issue I mentioned before, and leave this open for now.

**Comment by plunkettgoogle** [comment]
Actually, the bug I found doesn't really have anything to do with the bug described here, so I'll just open a separate issue.
